#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v13
# autospec commit: 2659038
#
# Source0 file verified with key 0x996DDA075594ADB8 (joel@debian.org)
#
Name     : ccache
Version  : 4.10.1
Release  : 77
URL      : https://github.com/ccache/ccache/releases/download/v4.10.1/ccache-4.10.1.tar.gz
Source0  : https://github.com/ccache/ccache/releases/download/v4.10.1/ccache-4.10.1.tar.gz
Source1  : https://github.com/ccache/ccache/releases/download/v4.10.1/ccache-4.10.1.tar.gz.asc
Source2  : 996DDA075594ADB8.pkey
Source3  : ccache.sh
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-3.0+
Requires: ccache-bin = %{version}-%{release}
Requires: ccache-data = %{version}-%{release}
Requires: ccache-license = %{version}-%{release}
Requires: ccache-man = %{version}-%{release}
BuildRequires : asciidoctor
BuildRequires : buildreq-cmake
BuildRequires : fmt
BuildRequires : fmt-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : xxHash-dev
BuildRequires : zlib-dev
BuildRequires : zstd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-fmt-detect.patch

%description
This directory contains Dockerfiles for building and testing ccache in
different build environments.

%package bin
Summary: bin components for the ccache package.
Group: Binaries
Requires: ccache-data = %{version}-%{release}
Requires: ccache-license = %{version}-%{release}

%description bin
bin components for the ccache package.


%package data
Summary: data components for the ccache package.
Group: Data

%description data
data components for the ccache package.


%package license
Summary: license components for the ccache package.
Group: Default

%description license
license components for the ccache package.


%package man
Summary: man components for the ccache package.
Group: Default

%description man
man components for the ccache package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 996DDA075594ADB8' gpg.status
%setup -q -n ccache-4.10.1
cd %{_builddir}/ccache-4.10.1
%patch -P 1 -p1
pushd ..
cp -a ccache-4.10.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719985980
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DREDIS_STORAGE_BACKEND=OFF \
-DDEPS=LOCAL \
-DENABLE_TESTING=OFF  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DREDIS_STORAGE_BACKEND=OFF \
-DDEPS=LOCAL \
-DENABLE_TESTING=OFF  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :
cd ../../buildavx2/clr-build-avx2;
make test || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719985980
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ccache
cp %{_builddir}/ccache-%{version}/LICENSE.adoc %{buildroot}/usr/share/package-licenses/ccache/6f92254676bb555fe863175e97e68bea6852c1d1 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/share/defaults/etc/profile.d
install  %{_sourcedir}/ccache.sh %{buildroot}/usr/share/defaults/etc/profile.d/
## install_append content
mkdir -p %{buildroot}/usr/lib64/ccache/bin
for f in cc c++ cpp \
{x86_64-generic-linux-,}{gcc,g++}{,-8,-9} \
{clang,clang++}{,-8,-9,-10}; do
ln -s ../../../bin/ccache %{buildroot}/usr/lib64/ccache/bin/$f
done
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/ccache/bin/c++
/usr/lib64/ccache/bin/cc
/usr/lib64/ccache/bin/clang
/usr/lib64/ccache/bin/clang++
/usr/lib64/ccache/bin/clang++-10
/usr/lib64/ccache/bin/clang++-8
/usr/lib64/ccache/bin/clang++-9
/usr/lib64/ccache/bin/clang-10
/usr/lib64/ccache/bin/clang-8
/usr/lib64/ccache/bin/clang-9
/usr/lib64/ccache/bin/cpp
/usr/lib64/ccache/bin/g++
/usr/lib64/ccache/bin/g++-8
/usr/lib64/ccache/bin/g++-9
/usr/lib64/ccache/bin/gcc
/usr/lib64/ccache/bin/gcc-8
/usr/lib64/ccache/bin/gcc-9
/usr/lib64/ccache/bin/x86_64-generic-linux-g++
/usr/lib64/ccache/bin/x86_64-generic-linux-g++-8
/usr/lib64/ccache/bin/x86_64-generic-linux-g++-9
/usr/lib64/ccache/bin/x86_64-generic-linux-gcc
/usr/lib64/ccache/bin/x86_64-generic-linux-gcc-8
/usr/lib64/ccache/bin/x86_64-generic-linux-gcc-9

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ccache
/usr/bin/ccache

%files data
%defattr(-,root,root,-)
/usr/share/defaults/etc/profile.d/ccache.sh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ccache/6f92254676bb555fe863175e97e68bea6852c1d1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ccache.1
